name: MeuPrimeirWorkflow

on:
  push:
    branches: [ "main", "develop" ]
jobs:
  test_job:
    name: Executando job de teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run a multi-line script
      run: echo "Meu projeto YAML com a FIAP".
