name: MeuPrimeirWorkflow

on:
  push:
    branches: 
      - 'main'
      - 'wip/*'
      - 'release/[0-9]+\.[0-9]+\.[0-9]+'
    #types:
      #- commit
      # - update
jobs:
  test_job:
    name: Executando job de teste
    runs-on: self-hosted
    steps:
    - name: Step 01
      uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: 'gsramos'
        password: ${{secrets.DOCKER_HUB_SECRET}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        tags: 'latest'
        push: true